const javaKeywords = new Set([
  'abstract','assert','boolean','break','byte','case','catch','char','class','const','continue','default','do','double','else','enum','extends','final','finally','float','for','goto','if','implements','import','instanceof','int','interface','long','native','new','package','private','protected','public','return','short','static','strictfp','super','switch','synchronized','this','throw','throws','transient','try','void','volatile','while'
])

export function toPascalCase(s: string): string {
  const parts = s
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
  const out = parts.map(p => p[0]?.toUpperCase() + p.slice(1)).join('')
  if (!out) return 'AutoGenerated'
  if (/^[0-9]/.test(out)) return '_' + out
  if (javaKeywords.has(out.toLowerCase())) return out + 'Model'
  return out
}

export function toCamelCase(s: string): string {
  const pascal = toPascalCase(s)
  return pascal[0].toLowerCase() + pascal.slice(1)
}

export function safeJavaIdentifier(s: string, preferCamel = false): string {
  const name = preferCamel ? toCamelCase(s) : toPascalCase(s)
  if (javaKeywords.has(name.toLowerCase())) return name + 'Field'
  return name
}

export function preserveSafeName(s: string): string {
  // replace invalid characters with underscore
  let name = String(s).replace(/[^A-Za-z0-9_]/g, '_')
  if (!name) name = 'field'
  if (/^[0-9]/.test(name)) name = '_' + name
  if (javaKeywords.has(name.toLowerCase())) name = name + 'Field'
  return name
}
